project:
  type: website
  #output-dir: docs

website:
  title: "ACA@NeurIPS"
  navbar:
    search: false
    background: "#243B59"
    right:
      # - href: index.qmd
      #   text: About
      - href: about.qmd
        text: About
      - href: accepted-papers.qmd
        text: Accepted Papers
      #- href: schedule.qmd
      #  text: Schedule
      - href: cfp.qmd
        text: ðŸ“£ Call for Papers
      # - href: speakers/index.qmd
      #   text: Our Speakers
      # - href: team.qmd
      #   text: Our Team

  page-footer: 
    center: "Contact us at acaworkshop2025@gmail.com"
    background: "#006296"
      

format:
  html:
    page-layout: full
  
    # title-block-banner: images/banner-5.jpg
    # title-block-banner-color: "white"

    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



